test_cases = [
    {
        'assembly': 'add x1, x2, x3',
        'inst': '003100B3',
        'ImmSel': '00',
        'ALUSrc_B': '0',
        'MemtoReg': '00',
        'Jump': '0',
        'Branch': '0',
        'RegWrite': '1',
        'MemRW': '0',
        'ALU_Control': '010',
        'CPU_MIO': '0'
    },
    {
        'assembly': 'addi x2, x1, 1',
        'inst': '00108113',
        'ImmSel': '01',
        'ALUSrc_B': '1',
        'MemtoReg': '00',
        'Jump': '0',
        'Branch': '0',
        'RegWrite': '1',
        'MemRW': '0',
        'ALU_Control': '010',
        'CPU_MIO': '0'
    },
    {
        'assembly': 'lw x2, 0(x1)',
        'inst': '0000A103',
        'ImmSel': '01',
        'ALUSrc_B': '1',
        'MemtoReg': '01',
        'Jump': '0',
        'Branch': '0',
        'RegWrite': '1',
        'MemRW': '0',
        'ALU_Control': '010',
        'CPU_MIO': '1'
    },
    {
        'assembly': 'sw x2, 0(x1)',
        'inst': '0020A023',
        'ImmSel': '10',
        'ALUSrc_B': '1',
        'MemtoReg': '00',
        'Jump': '0',
        'Branch': '0',
        'RegWrite': '0',
        'MemRW': '1',
        'ALU_Control': '010',
        'CPU_MIO': '1'
    },
    {
        'assembly': 'beq x5, x6, -8',
        'inst': 'FE628CE3',
        'ImmSel': '11',
        'ALUSrc_B': '0',
        'MemtoReg': '00',
        'Jump': '0',
        'Branch': '1',
        'RegWrite': '0',
        'MemRW': '0',
        'ALU_Control': '110',
        'CPU_MIO': '0'
    },
    {
        'assembly': 'jalr x1, x5, 100',
        'inst': '064280E7',
        'ImmSel': '01',
        'ALUSrc_B': '1',
        'MemtoReg': '10',
        'Jump': '1',
        'Branch': '0',
        'RegWrite': '1',
        'MemRW': '0',
        'ALU_Control': '010',
        'CPU_MIO': '0'
    }
]